name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH keys for GitHub
        env:
          HUB_DEPLOY_KEY: ${{ secrets.HUB_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$HUB_DEPLOY_KEY" > ~/.ssh/github_ssh_key
          chmod 600 ~/.ssh/github_ssh_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/github_ssh_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Connect to DigitalOcean and deploy
        env:
          DO_PRIVATE_KEY: ${{ secrets.DO_PRIVATE_KEY }}
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USER: ${{ secrets.DO_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$DO_PRIVATE_KEY" > ~/.ssh/DO_nops
          chmod 600 ~/.ssh/DO_nops
          ssh-keyscan $DO_HOST >> ~/.ssh/known_hosts

          # SSH into DigitalOcean and deploy
          ssh -i ~/.ssh/DO_nops -o StrictHostKeyChecking=no $DO_USER@$DO_HOST << 'EOF'
            cd /path/to/your/project  # Change to your project directory
            git pull origin main  # Pull latest changes
            npm install  # Install dependencies (if needed)
            npm run build  # Build (if needed)
            pm2 restart app  # Restart the application (if using PM2)
          EOF
