name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH keys for GitHub
        env:
          HUB_DEPLOY_KEY: ${{ secrets.HUB_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$HUB_DEPLOY_KEY" > ~/.ssh/github_ssh_key
          chmod 600 ~/.ssh/github_ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_ssh_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global core.sshCommand "ssh -i ~/.ssh/github_ssh_key"

      - name: Set up SSH keys for DigitalOcean
        env:
          DO_PRIVATE_KEY: ${{ secrets.DO_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DO_PRIVATE_KEY" > ~/.ssh/DO_nops
          chmod 600 ~/.ssh/DO_nops
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/DO_nops
          ssh-keyscan ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Connect to DigitalOcean and deploy
        env:
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USER: ${{ secrets.DO_USER }}
        run: |
          ssh -i ~/.ssh/DO_nops -o StrictHostKeyChecking=no $DO_USER@$DO_HOST << 'EOF'
            cd /var/www/Haskins_House/  
            git pull origin main || { echo "Git pull failed"; exit 1; }
            npm install || { echo "NPM install failed"; exit 1; }

            if grep -q '"build":' package.json; then
              npm run build || { echo "Build failed"; exit 1; }
            else
              echo "Skipping build step (no build script found)"
            fi

            pm2 restart app || pm2 start app.js --name app || { echo "PM2 failed"; exit 1; }
          EOF
